name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js for server (backend)
    - name: Use Node.js for server (backend)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./server/package-lock.json"

    - name: Install server dependencies
      working-directory: ./server
      run: npm ci
    
    # Build the server (backend)
    - name: Build server (backend)
      working-directory: ./server
      run: npm run build --if-present
    
    # Setup Node.js for client (frontend)
    - name: Use Node.js for client (frontend)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./client/package-lock.json"

    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
    
    # Build the client (frontend)
    - name: Build client (frontend)
      working-directory: ./client
      run: npm run build --if-present
